routes/web.php
<?php

// Web

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use App\Image;

Route::get('/', 'Web\PageController@index')->name('page.index');
Route::get('categoria/{slug}', 'Web\PageController@category')->name('page.category');
Route::get('etiqueta/{slug}', 'Web\PageController@tag')->name('page.tag');

Route::get('/articulos', 'Web\PageController@more_product')->name('page.more_product');
Route::get('/detalle/{product}', 'Web\PageController@detail_product')->name('page.detail_product');
Route::post('articulo/store',    'Web\PageController@store')->name('articulo.store'); //->middleware('can:products.create');
Route::put('articulo/{product}/', 'Web\PageController@update')->name('articulo.update'); //->middleware('can:products.edit');
Route::post('articulo/sold/{product}/', 'Web\PageController@soldproduct')->name('articulo.soldproduct'); //->middleware('can:products.edit');
Route::get('articulo/Published/{product}/', 'Web\PageController@PublishedProduct')->name('articulo.PublishedProduct'); //->middleware('can:products.edit');
Route::get('articulo/reservar/{product}/', 'Web\PageController@reservedProduct')->name('articulo.reservar'); //->middleware('can:products.edit');
Route::get('/comprar/{product}', 'Web\PageController@comprar')->name('page.comprar');
Route::post('comprar/store/{product}',    'Web\PageController@comprar_store')->name('comprar.store');
Route::get('/homestaging', function () { return view('homestaging');})->name('homestaging');
Route::get('/saldos', function () { return view('saldos');})->name('saldos');
Route::get('/restauracion', function () { return view('restauracion');})->name('restauracion');
Route::get('/nosotros', function () { return view('nosotros');})->name('nosotros');
Route::get('/privacidad-cookies', function () { return view('politica-privacidad');})->name('politicas');
Route::get('/como-funciona', function () { return view('como-funciona');})->name('how_func');
Route::get('/terminos-condiciones', function () { return view('terminos-condiciones');})->name('terminos-condiciones');
// Route::get('/privacidad-cookies', function () { return response(view('politica-privacidad'))->cookie('Politicas','valor', 1);})->name('politicas');
Route::get('/como-vender', 'Web\PageController@to_sell')->name('page.to_sell');
Route::get('/como-comprar', 'Web\PageController@to_buy')->name('page.to_buy');
Route::get('/contact', 'Web\PageController@contacto')->name('contact');
Route::post('/contact', 'ContactoController@store')->name('contact.store');

Route::get('/welcome','MailSend@welcome');
Auth::routes(['verify' => true]);

Route::get('/img_product/{attachment}', function($attachment) {
    $file = sprintf('public/%s', $attachment);
    if(File::exists($file)) {
        return Image::make($file)->response();
    }
});
Route::get('Contrato/excel/{agreement}', 'Web\PageController@downloadExcel')->name('agreements.excel');

Auth::routes();
// admin
Route::middleware(['auth'])->group(function () {
    Route::get('/quiero-vender', 'Web\PageController@quiero_vender')->name('quiero-vender');
    Route::get('/form-vender', 'Web\PageController@form_product')->name('form-vender');
    Route::get('/form-visit', 'Web\PageController@form_visit')->name('form-visit');

    Route::get('/detalle/{product}/edit', 'Web\PageController@detail_edit_product')->name('page.detail_edit_product');
    Route::get('/mis_productos', 'Web\PageController@client_products')->name('client_products');
    Route::get('/Contrato/{agreement}/', 'Web\PageController@detail_client_agreement')->name('contrato.detalle');
    Route::get('/Contrato/pass_agreement/{token}', 'Web\PageController@pass_agreement')->name('pass.contrato');
    Route::get('/Contrato/DownloadPdf/{agreement}/', 'Web\PageController@download_pdf')->name('contrato.download');
    Route::delete('/articulo/de_baja/{product}/', 'Web\PageController@destroy')->name('article.destroy');
    Route::get('/editProfile', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/update/{user}', 'ProfileController@update')->name('profile.update');
    Route::post('visits/store',       'VisitController@store')->name('visits.store');
    Route::get('qr-products/{product}',     'Admin\ProductController@qr_products')->name('products.qr_products');
    Route::delete('visits/remove/images/{image}',    'VisitController@removeImage')->name('removeImage');
    Route::post('products/assign_portada/{product}',     'Admin\ProductController@assign_portada')->name('products.assign_portada');

    // ========admin===========
    Route::get('company/details', 'CompanyController@index')->name('company.show')->middleware('admin');
    Route::get('company/{company}/edit', 'CompanyController@edit')->name('company.edit')->middleware('admin');
    Route::put('company/{company}/update', 'CompanyController@update')->name('company.update');

    Route::get('/admin', 'Web\AdminController@index')->name('admin')->middleware('admin');
    Route::get('/admin/profile/{user}', 'Web\AdminController@profile')->name('profile')->middleware('admin');
    Route::resource('categories',   'Admin\CategoryController')->middleware('admin');;
    Route::resource('tags',         'Admin\TagController')->middleware('admin');;

    // routes for products
    Route::get('/admin/products',       'Admin\ProductController@index')->name('products.index')->middleware('admin');
    Route::get('/admin/products/outled',       'Admin\ProductController@outet')->name('products.outet')->middleware('admin');
    Route::get('/admin/products/register', 'Admin\ProductController@create')->name('products.create')->middleware('admin');
    Route::get('/admin/products/sinDescuento/register', 'Admin\ProductController@createSinDecuento')->name('products.createSinDecuento')->middleware('admin');
    Route::get('/admin/products/beliani/register', 'Admin\ProductController@createBeliani')->name('products.createBeliani')->middleware('admin');
    Route::get('/admin/products/beliani/{product}/convert', 'Admin\ProductController@toBeliani')->name('products.toBeliani')->middleware('admin');
    Route::post('products/store',       'Admin\ProductController@store')->name('products.store');
    Route::put('products/{product}/update', 'Admin\ProductController@update')->name('products.update');
    Route::get('products/{product}',        'Admin\ProductController@show')->name('products.show')->middleware('admin');
    Route::delete('delete/products/{product}/basico',     'Admin\ProductController@destroy')->name('products.destroy.debaja');
    Route::get('products/{product}/rechazar',   'Admin\ProductController@regected')->name('products.regected')->middleware('admin');
    Route::put('products/rechazar/{product}',     'Admin\ProductController@rechazar')->name('products.rechazar');
    Route::post('products/more_images/{product}',     'Admin\ProductController@more_images')->name('products.more_images');
    Route::put('products/reservar/{product}',       'Admin\ProductController@reservar')->name('products.reservar');
    Route::put('products/publicNow/{product}',       'Admin\ProductController@detenerReserva')->name('products.detenerReserva');
    Route::put('products/ConcluirArticulo/{product}',       'Admin\ProductController@concluirArticulo')->name('products.concluirArticulo');
    Route::put('products/ConcluirArticulo/{product}',       'Admin\ProductController@venderConcluido')->name('products.vender.concluido');
    Route::get('products/{product}/edit',   'Admin\ProductController@edit')->name('products.edit')->middleware('admin');
    Route::put('publicar/{product}/',      'Admin\ProductController@publicar')->name('products.publicar');
    Route::post('products/img_default/{product}',     'Admin\ProductController@img_default')->name('products.img_default');

    Route::get('/admin/products/pendientes',       'Admin\ProductController@pendientes')->name('products.pendientes')->middleware('admin');
    Route::get('/admin/products/debaja',       'Admin\ProductController@debaja')->name('products.debaja')->middleware('admin');
    Route::get('/admin/products/reservados',       'Admin\ProductController@reservados')->name('products.reservados')->middleware('admin');
    Route::get('/admin/products/reservadosBasicos',       'Admin\ProductController@reservadosBasicos')
        ->name('products.reservadosBasicos')->middleware('admin');

    //agreements
    Route::delete('products/{product}',     'AgreementController@elminarArticulo')->name('contrato.products.destroy');
    Route::get('agreements', 'AgreementController@index')->name('agreements.index')->middleware('admin');
    Route::get('agreements/create', 'AgreementController@create')->name('agreements.create')->middleware('admin');
    Route::post('agreements/store',       'VisitController@store')->name('agreements.store');
    Route::get('agreements/{agreement}/show', 'AgreementController@show')->name('agreements.show')->middleware('admin');
    Route::get('agreements/{agreement}/details', 'AgreementController@details')->name('agreements.detail')->middleware('admin');
    Route::get('agreements/{agreement}/edit', 'AgreementController@edit')->name('agreements.edit')->middleware('admin');
    Route::put('agreements/{agreement}/update', 'AgreementController@update')->name('agreements.update');
    Route::put('agreements/concluir/{agreement}', 'AgreementController@concluirContrato')->name('agreements.concluirContrato');
    Route::put('agreements/cambiar/{agreement}', 'AgreementController@changeAgreement')->name('agreements.change');
    Route::delete('agreements/eliminar/{agreement}', 'AgreementController@destroy')->name('agreements.destroy');
    Route::get('agreements/verify/{token}', 'AgreementController@verifyAgreement')->name('agreements.verify');
    Route::get('agreements/export/{agreement}/', 'AgreementController@export')->name('agreements.export')->middleware('admin');

app/Compra.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Compra extends Model
{
    protected $fillable = [
        'product_id',
        'vendedor',
        'comprador',
        'status',
        'nameClient',
        'email',
        'phone',
        'city',
        'comments',
        'monto_reserva',
        'have_reserva',
        'pago',
        'have_pago',
        'fecha_reserva',
        'fecha_venta',
    ];

    public function getSellerAttribute()
    { // vendedor
        return User::where('id', $this->vendedor)->first();
    }

    public function product()
    { // a user can have many products
        return $this->belongsTo(Product::class);
    }

    public function getBuyerAttribute()
    { // cliente, comprador
        return User::where('id', $this->comprador)->first();
    }
}

resources/views/admin/compras/CompraForm.blade.php
{!! Form::open(['route' => ['compras.store', $product], 'onclick' => 'return confirm("Estas seguro de vender el artículo?")']) !!}
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="name">Nombre de comprador</label>
            @if (auth()->user())
            <input id="name" name="name" type="text" value="" required class="form-control"
                placeholder="Nombre">
            @else
            <input id="name" name="name" type="text" required class="form-control" placeholder="Nombre">
            @endif
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <label for="email">Correo del comprador</label>
            @if (auth()->user())
            <input id="email" name="email" type="email" value="" required
                class="form-control" placeholder="Correo">
            @else
            <input id="email" name="email" type="email" required class="form-control" placeholder="Correo">
            @endif
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <label for="phone">Teléfono </label>
            @if (auth()->user())
            <input id="phone" name="phone" type="phone" value="" required
                class="form-control" placeholder="Teléfono">
            @else
            <input id="phone" name="phone" type="phone" required class="form-control" placeholder="Teléfono">
            @endif
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <label for="city">Ciudad ó Codigo Postal</label>
            @if (auth()->user())
            <input id="city" name="city" type="text" value="" required
                class="form-control" placeholder="Ciudad ó Codigo Postal">
            @else
            <input id="city" name="city" type="text" required class="form-control" placeholder="Ciudad ó Codigo Postal">
            @endif
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label for="comments">Consultas y comentarios</label>
            <textarea id="comments" name="comments" class="form-control" placeholder="Consultas y comentarios"
                rows="3">Articulo Vendido</textarea>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group text-center">
            <b>Precio Final de Venta :</b>
            @if ($product->reduced_price)
            <input id="pago" name="pago" type="number" min="0" step=".01" required
                class="form-control" placeholder="Importe" value="{{ $product->reduced_price}}">
            @else
            <input id="pago" name="pago" type="number" min="0" step=".01" value="{{ $product->normal_price}}" required class="form-control">
            @endif
            <i class="fa fa-euro"></i>
        </div>
    </div>
    <div class="col-md-12 text-center">
        <input name="have_pago" value="GESTOR" type="radio" id="radio2_{{$product->id}}" checked>
        <label for="radio2_{{$product->id}}">Gestor</label>

        <input name="have_pago" value="CLIENTE" type="radio" id="radio01_{{$product->id}}_1">
        <label for="radio01_{{$product->id}}_1">Cliente</label>
    </div>

    <div class="col-md-12 text-center">
        <input type="submit" class="btn btn-success" value="Marcar Articulo Vendido" />
    </div>
</div>
{!! Form::close() !!}

resources/views/admin/compras/articlesReservados.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="box box-solid bg-dark">
            <div class="box-header with-border">
                <h3 class="box-title">Reservados</h3>
                {{-- <a href="{{ route ('products.create')}}" class="btn btn-info float-right">Registrar</a> --}}
                <h6 class="box-subtitle"> Listado de Articulos Reservados</h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#Reservados" role="tab"><span><i
                                    class="fa  fa-file"></i></span> Articulos Reservados </a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content tabcontent-border">
                    <div class="tab-pane active" id="Reservados" role="tabpanel">
                        <div class="pad">
                            <table class="table table-striped">
                                <thead>
                                    <th>#</th>
                                    <th>Cliente</th>
                                    <th>telefono</th>
                                    <th>Email</th>
                                    <th>Producto</th>
                                    <th>Vendedor</th>
                                    {{-- <th>Fecha Reservado</th> --}}
                                    <th>Importe</th>
                                    <th>Fecha Reserva</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach($compras as $compra)
                                    <tr>
                                        <th> {{ $loop->iteration }}</th>
                                        {{-- <td> <a href="{{ route ('agreements.show', $compra) }}">
                                        {{ $compra->name }} </a> </td> --}}
                                        <td>
                                            @if ($compra->comprador)
                                            <a class="text-warning" href="{{ route ('profile', $compra->buyer) }}">
                                                {{ $compra->buyer->name }} {{ $compra->buyer->profile->last_name}}
                                            </a>
                                            @else
                                            {{ $compra->nameClient }}
                                            @endif
                                        </td>
                                        <td>
                                            <a href="https://web.whatsapp.com/send?phone={{ $compra->phone }}" class="btn btn-primary btn-sm"
                                                target="_blank">
                                                <i class="fa fa-whatsapp"></i>
                                                {{$compra->phone}}</a>
                                        </td>
                                        <td>{{ $compra->email }}</td>
                                        <td><a class="text-primary" href="{{ route ('products.show', $compra->product) }}">
                                                {{ $compra->product->name }} </a></td>
                                        <td><a class="text-success" href="{{ route ('profile', $compra->seller) }}">
                                                {{ $compra->seller->name}} </a></td>
                                        <td> <span class="text-danger"> {{ $compra->monto_reserva}} <i class="fa fa-euro"></i>
                                            </span> {{ $compra->have_reserva}}</td>
                                        <td> {{ date('d-m-Y', strtotime($compra->fecha_reserva)) }} </td>
                                        <td>
                                            {{-- <a class="btn btn-sm btn-primary" href="{{ route ('compras.show', $compra) }}"> Ver</a> --}}
                                            <a class="btn btn-sm btn-success" href="{{ route ('compras.create', $compra->product) }}"> Completar
                                                Venta</a>
                                            {!! Form::open(['route' =>['products.detenerReserva', $compra->product], 'method' =>
                                            'PUT', 'class' => ['inline'] ]) !!}
                                            <button class="btn btn-sm btn-danger"> Detener Reserva</button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <nav class="mt-15 pb-10">
                    <ul class="pagination justify-content-center">
                        {{ $compras->links() }}
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>

@endsection

resources/views/admin/compras/articlesSolds.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="box box-solid bg-dark">
            <div class="box-header with-border">
                <h3 class="box-title">Ventas</h3>
                {{-- <a href="{{ route ('products.create')}}" class="btn btn-info float-right">Registrar</a> --}}
                <h6 class="box-subtitle"> Listado de Articulos Vendidos</h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#vendidos"
                            role="tab"><span><i class="fa  fa-file"></i></span> Articulos Vendidos </a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content tabcontent-border">
                    <div class="tab-pane active" id="vendidos" role="tabpanel">
                        <div class="pad">
                            <table class="table table-striped">
                                <thead>
                                    <th>#</th>
                                    <th>Cliente</th>
                                    <th>telefono</th>
                                    <th>Email</th>
                                    <th>Producto</th>
                                    <th>Gestor</th>
                                    {{-- <th>Fecha Completado</th> --}}
                                    <th>Importe</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach($compras as $compra)
                                    <tr>
                                        <th> {{ $loop->iteration }}</th>
                                        {{-- <td> <a href="{{ route ('agreements.show', $compra) }}">
                                        {{ $compra->name }} </a> </td> --}}
                                        <td>
                                            @if ($compra->comprador)
                                            <a class="text-warning" href="{{ route ('profile', $compra->buyer) }}">
                                                {{ $compra->buyer->name }} {{ $compra->buyer->profile->last_name}}
                                            </a>
                                            @else
                                            {{ $compra->nameClient }}
                                            @endif
                                        </td>
                                        <td>
                                            <a href="https://web.whatsapp.com/send?phone={{ $compra->phone }}"
                                                class="btn btn-primary btn-sm" target="_blank">
                                                <i class="fa fa-whatsapp"></i>
                                                {{$compra->phone}}</a>
                                        </td>
                                        <td>{{ $compra->email }}</td>
                                        <td><a class="text-primary"
                                                href="{{ route ('products.show', $compra->product) }}">
                                                {{ $compra->product->name }} </a></td>
                                        <td><a class="text-success" href="{{ route ('profile', $compra->seller) }}">
                                                {{ $compra->seller->name}} </a></td>
                                        {{-- <td>{{ $compra->updated_at }}</td> --}}
                                        <td> <span class="text-danger">  {{ $compra->pago}} <i class="fa fa-euro"></i>
                                            </span></td>
                                        <td>
                                            <a class="btn btn-sm btn-primary"
                                                href="{{ route ('compras.show', $compra) }}"> Ver Venta</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <nav class="mt-15 pb-10">
                    <ul class="pagination justify-content-center">
                        {{ $compras->links() }}
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>

@endsection

resources/views/admin/compras/create.blade.php
@extends('layouts.admin')

@section('content')

<div class="box box-solid bg-dark">
	<div class="box-header with-border">
		<h3 class="box-title">Registrar Artículo</h3>
        {{-- <h6 class="box-subtitle"> Registrar un articulo para la venta</h6> --}}
        <a href="{{ route ('products.index')}}" class="btn btn-danger float-right">Cancelar</a>
	</div>
	<!-- /.box-header -->
	<div class="box-body">
		{!! Form::open(['route' => 'products.store', 'files' =>true ]) !!}	
			@include('admin.products.productForm')
		{!! Form::close() !!}
	</div>
	<div class="box-footer">
		vista previa del articulo
	</div>
</div>

@endsection

resources/views/admin/compras/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="box box-solid bg-dark">
            <div class="box-header with-border">
                <h3 class="box-title">Compras Solicitadas</h3>
                {{-- <a href="{{ route ('products.create')}}" class="btn btn-info float-right">Registrar</a> --}}
                <h6 class="box-subtitle"> Listado de Solicitudes</h6>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#solicitudes" role="tab"><span><i
                                    class="fa  fa-file"></i></span> Solicitudes </a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content tabcontent-border">
                    <div class="tab-pane active" id="solicitudes" role="tabpanel">
                        <div class="pad">
                            <table class="table table-striped">
                                <thead>
                                    <th>#</th>
                                    <th>Cliente</th>
                                    <th>Fecha Solicitud</th>
                                    <th>telefono</th>
                                    <th>Email</th>
                                    <th>Descripcion</th>
                                    <th>Producto</th>
                                    <th>Contrato</th>
                                    {{-- <th>Fecha Solicitada</th> --}}
                                    <th>Importe</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach($compras as $compra)
                                    <tr>
                                        <th> {{ $loop->iteration }}</th>
                                        <td>
                                            @if ($compra->comprador)
                                            <a class="text-warning" href="{{ route ('profile', $compra->buyer) }}">
                                                {{ $compra->buyer->name }} {{ $compra->buyer->profile->last_name}}
                                            </a>
                                            @else
                                            {{ $compra->nameClient }}
                                            @endif
                                        </td>
                                        <td>
                                            {{-- <a href="{{ route ('agreements.show', $compra) }}" class="btn"> --}}
                                                {{ date('d-m-Y', strtotime($compra->created_at)) }}
                                            {{-- </a> --}}
                                        </td>
                                        <td>
                                            <a class="btn btn-success btn-xs mx-2 text-white hover-info"
                                                href="https://web.whatsapp.com/send?phone={{ $compra->phone }}" target="_blank">
                                                <i class="fa fa-whatsapp"></i> {{$compra->phone}}</a>
                                        </td>
                                        <td>{{ $compra->email }}</td>
                                        <td>{{ $compra->comments }}</td>
                                        <td><a class="text-primary" href="{{ route ('products.show', $compra->product) }}">
                                                {{ $compra->product->name }} </a></td>
                                        <td> {{ $compra->product->code }}</td>
                                        {{-- <td><a class="text-success" href="{{ route ('profile', $compra->seller) }}"> {{
                                                $compra->seller->name}}
                                            </a></td> --}}

                                        {{-- <td>{{ $compra->created_at }}</td> --}}
                                        <td> <span class="text-danger"> {{ $compra->pago}} <i class="fa fa-euro"></i> </span></td>
                                        <td>
                                            {{-- <a class="btn btn-sm btn-primary" href="{{ route ('compras.show', $compra) }}"> Ver</a> --}}
                                            <a class="btn btn-sm btn-default" href="{{ route ('compras.create', $compra->product) }}"> Completar
                                                Venta</a>
                                            {!! Form::open(['route' =>['compras.destroy', $compra], 'method' => 'delete',
                                            'class' => ['inline'],'onclick' => 'return confirm("Estas seguro de eliminar la solicitud?")' ]) !!}
                                            <button class="btn btn-sm btn-danger"> Eliminar Sol.</button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <nav class="mt-15 pb-10">
                    <ul class="pagination justify-content-center">
                        {{ $compras->links() }}
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>

@endsection